version: "3.7"
services:
    app:
        build: .
        container_name: app-rooster
        volumes:
            - ./src:/var/www
        networks:
            - cookbooks
        environment:
          - COMPOSER_ALLOW_SUPERUSER=1
    
    nginx:
        image: nginx:alpine
        container_name: web-rooster
        restart: unless-stopped
        ports:
            - "8087:80"
        volumes:
            - ./src:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - cookbooks

networks:
    cookbooks:
        driver: bridge
