version: "3.7"
services:
    app-crm:
        build: .
        container_name: app-crm
        volumes:
            - ./src:/var/www
        networks:
            - reap_network
        environment:
          - COMPOSER_ALLOW_SUPERUSER=1
    
    nginx-crm:
        image: nginx:alpine
        container_name: web-crm
        restart: unless-stopped
        ports:
            - "8222:80"
        volumes:
            - ./src:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - reap_network

networks:
  reap_network:
    external: true
